export { default as BadRequest } from "./bad-request"; // 400
export { default as Unauthorized } from "./unauthorized"; // 401
export { default as PaymentRequired } from "./payment-required"; // 402
export { default as Forbidden } from "./forbidden"; // 403
export { default as NotFound } from "./not-found"; // 404
export { default as MethodNotAllowed } from "./method-not-allowed"; // 405
export { default as NotAcceptable } from "./not-acceptable"; // 406
export { default as ProxyAuthenticationRequired } from "./proxy-authentication-required"; // 407
export { default as RequestTimeout } from "./request-timeout"; // 408
export { default as Conflict } from "./conflict"; // 409
export { default as Gone } from "./gone"; // 410
export { default as LengthRequired } from "./length-required"; // 411
export { default as PreconditionFailed } from "./precondition-failed"; // 412
export { default as PayloadTooLarge } from "./payload-too-large"; // 413
export { default as UriTooLong } from "./uri-too-long"; // 414
export { default as UnsupportedMediaType } from "./unsupported-media-type"; // 415
export { default as RequestedRangeNotSatisfiable } from "./requested-range-not-satisfiable"; // 416
export { default as ExpectationFailed } from "./expectation-failed"; // 417
export { default as ImATeapot } from "./im-a-teapot"; // 418
export { default as MisdirectedRequest } from "./misdirected-request"; // 421
export { default as UnprocessableEntity } from "./unprocessable-entity"; // 422
export { default as Locked } from "./locked"; // 423
export { default as FailedDependency } from "./failed-dependency"; // 424
export { default as UpgradeRequired } from "./upgrade-required"; // 426
export { default as PreconditionRequired } from "./precondition-required"; // 428
export { default as TooManyRequests } from "./too-many-requests"; // 429
export { default as RequestHeaderFieldsTooLarge } from "./request-header-fields-too-large"; // 431
export { default as UnavailableForLegalReasons } from "./unavailable-for-legal-reasons"; // 451