export { default as InternalServerError } from "./internal-server-error"; // 500
export { default as NotImplemented } from "./not-implemented"; // 501
export { default as BadGateway } from "./bad-gateway"; // 502
export { default as ServiceUnavailable } from "./service-unavailable"; // 503
export { default as GatewayTimeout } from "./gateway-timeout"; // 504
export { default as HttpVersionNotSupported } from "./http-version-not-supported"; // 505
export { default as VariantAlsoNegotiates } from "./variant-also-negotiates"; // 506
export { default as InsufficientStorage } from "./insufficient-storage"; // 507
export { default as LoopDetected } from "./loop-detected"; // 508
export { default as NotExtended } from "./not-extended"; // 510
export { default as NetworkAuthenticationRequired } from "./network-authentication-required"; // 511
